from __future__ import annotations

from app.models import SectionDefinition


SECTION_DEFINITIONS: dict[str, SectionDefinition] = {
    "modems": SectionDefinition(
        slug="modems",
        title="TNC",
        description="Manage TNC definitions for the split APRSBox core/web architecture. Runtime TNC handling is not implemented yet.",
        table_name="modems",
        nav_key="modems",
        readonly_message="TNC configuration is stored in SQLite for APRSBox core and web integration. Runtime TNC control comes later.",
        list_title="Configured TNC",
        create_title="Add TNC",
        edit_title="Edit TNC",
        supports_editing=True,
        supports_delete=True,
        fields=[
            {"name": "name", "label": "Name", "type": "text", "required": True},
            {
                "name": "band",
                "label": "Band",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "2m", "label": "2m"},
                    {"value": "70cm", "label": "70cm"},
                    {"value": "6m", "label": "6m"},
                ],
            },
            {
                "name": "modem_type",
                "label": "Type",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "SERIALL", "label": "SERIALL"},
                    {"value": "TCP", "label": "TCP"},
                ],
            },
            {"name": "device_path", "label": "Path / Adress", "type": "text", "required": False},
            {"name": "baud_rate", "label": "Baud Rate", "type": "number", "required": False},
            {"name": "enabled", "label": "Enabled", "type": "checkbox", "required": False},
            {"name": "notes", "label": "Notes", "type": "textarea", "required": False},
        ],
    ),
    "servers": SectionDefinition(
        slug="servers",
        title="APRS-IS Servers",
        description="Store APRS-IS upstream definitions for later engine integration.",
        table_name="aprsis_servers",
        nav_key="servers",
        readonly_message="Server definitions can be entered now, but APRS-IS connectivity is not implemented yet.",
        fields=[
            {"name": "name", "label": "Name", "type": "text", "required": True},
            {"name": "host", "label": "Host", "type": "text", "required": True},
            {"name": "port", "label": "Port", "type": "number", "required": True},
            {"name": "use_tls", "label": "Use TLS", "type": "checkbox", "required": False},
            {"name": "enabled", "label": "Enabled", "type": "checkbox", "required": False},
            {"name": "notes", "label": "Notes", "type": "textarea", "required": False},
        ],
    ),
    "igate": SectionDefinition(
        slug="igate",
        title="iGate Rules",
        description="Define future iGate policy entries. No packet transfer logic is implemented in this stage.",
        table_name="igate_rules",
        nav_key="igate",
        readonly_message="These records are placeholders for future iGate rule evaluation.",
        fields=[
            {"name": "name", "label": "Rule Name", "type": "text", "required": True},
            {"name": "direction", "label": "Direction", "type": "text", "required": True},
            {"name": "is_enabled", "label": "Enabled", "type": "checkbox", "required": False},
            {"name": "policy_text", "label": "Policy Notes", "type": "textarea", "required": False},
        ],
    ),
    "digi": SectionDefinition(
        slug="digi",
        title="DIGI Rules",
        description="Prepare digipeating rule definitions without implementing digipeating itself.",
        table_name="digi_rules",
        nav_key="digi",
        readonly_message="DIGI policy storage exists; packet path handling will be added later.",
        fields=[
            {"name": "name", "label": "Rule Name", "type": "text", "required": True},
            {"name": "source_match", "label": "Source Match", "type": "text", "required": False},
            {"name": "destination_match", "label": "Destination Match", "type": "text", "required": False},
            {"name": "path_rewrite", "label": "Path Rewrite", "type": "text", "required": False},
            {"name": "is_enabled", "label": "Enabled", "type": "checkbox", "required": False},
        ],
    ),
    "objects": SectionDefinition(
        slug="objects",
        title="Objects",
        description="Prepare APRS object records with protocol-safe names, status, position, symbol and future RF path.",
        table_name="aprs_objects",
        nav_key="objects",
        readonly_message="Object transmission is not implemented yet. APRS object names are stored unpadded here, but will later be encoded into the fixed 9-character APRS object field with an automatic timestamp.",
        list_title="Prepared Objects",
        create_title="Add Object",
        edit_title="Edit Object",
        supports_editing=True,
        supports_delete=True,
        fields=[
            {"name": "name", "label": "Object Name", "type": "text", "required": True, "maxlength": 9, "placeholder": "VOICE"},
            {
                "name": "lifetime",
                "label": "Object Lifetime",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "temporary", "label": "Temporary"},
                    {"value": "permanent", "label": "Permanent"},
                ],
            },
            {
                "name": "state",
                "label": "Object Activity",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "live", "label": "Live (*)"},
                    {"value": "killed", "label": "Killed (_)"},
                ],
            },
            {"name": "latitude", "label": "Latitude", "type": "text", "required": False},
            {"name": "longitude", "label": "Longitude", "type": "text", "required": False},
            {
                "name": "symbol_table",
                "label": "Symbol Table",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "/", "label": "Primary (/)"},
                    {"value": "\\", "label": "Alternate (\\)"},
                ],
            },
            {"name": "symbol_code", "label": "Symbol Code", "type": "text", "required": True, "maxlength": 1, "placeholder": "r"},
            {
                "name": "interval_minutes",
                "label": "Send Interval",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "5", "label": "5m"},
                    {"value": "10", "label": "10m"},
                    {"value": "15", "label": "15m"},
                    {"value": "30", "label": "30m"},
                    {"value": "45", "label": "45m"},
                    {"value": "60", "label": "60m"},
                ],
            },
            {"name": "path", "label": "Future RF Path", "type": "text", "required": False, "maxlength": 64, "placeholder": "WIDE2-2"},
            {"name": "is_enabled", "label": "Mark For Future Transmission", "type": "checkbox", "required": False},
            {"name": "comment", "label": "Comment", "type": "textarea", "required": False, "maxlength": 43, "placeholder": "Local voice repeater"},
        ],
    ),
    "items": SectionDefinition(
        slug="items",
        title="Items",
        description="Prepare APRS item records with protocol-safe names, status, position, symbol and future RF path.",
        table_name="aprs_items",
        nav_key="items",
        readonly_message="Item transmission is not implemented yet. APRS item names must be 3-9 printable ASCII characters and item format is historically less interoperable on RF than objects.",
        list_title="Prepared Items",
        create_title="Add Item",
        edit_title="Edit Item",
        supports_editing=True,
        supports_delete=True,
        fields=[
            {"name": "name", "label": "Item Name", "type": "text", "required": True, "maxlength": 9, "placeholder": "AID#2"},
            {
                "name": "state",
                "label": "Item State",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "live", "label": "Live (!)"},
                    {"value": "killed", "label": "Killed (_)"},
                ],
            },
            {"name": "latitude", "label": "Latitude", "type": "text", "required": False},
            {"name": "longitude", "label": "Longitude", "type": "text", "required": False},
            {
                "name": "symbol_table",
                "label": "Symbol Table",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "/", "label": "Primary (/)"},
                    {"value": "\\", "label": "Alternate (\\)"},
                ],
            },
            {"name": "symbol_code", "label": "Symbol Code", "type": "text", "required": True, "maxlength": 1, "placeholder": "A"},
            {
                "name": "interval_minutes",
                "label": "Send Interval",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "5", "label": "5m"},
                    {"value": "10", "label": "10m"},
                    {"value": "15", "label": "15m"},
                    {"value": "30", "label": "30m"},
                    {"value": "45", "label": "45m"},
                    {"value": "60", "label": "60m"},
                ],
            },
            {"name": "path", "label": "Future RF Path", "type": "text", "required": False, "maxlength": 64, "placeholder": "WIDE1-1,WIDE2-1"},
            {"name": "is_enabled", "label": "Mark For Future Transmission", "type": "checkbox", "required": False},
            {"name": "comment", "label": "Comment", "type": "textarea", "required": False, "maxlength": 43, "placeholder": "First aid station"},
        ],
    ),
    "bulletins": SectionDefinition(
        slug="bulletins",
        title="Bulletins",
        description="Store bulletin text and cadence metadata for future APRS scheduling.",
        table_name="bulletins",
        nav_key="bulletins",
        readonly_message="Bulletin definitions can be stored now. Broadcast scheduling comes later.",
        fields=[
            {"name": "name", "label": "Bulletin Name", "type": "text", "required": True},
            {"name": "body", "label": "Body", "type": "textarea", "required": True},
            {"name": "cadence_minutes", "label": "Cadence (minutes)", "type": "number", "required": False},
            {"name": "is_enabled", "label": "Enabled", "type": "checkbox", "required": False},
        ],
    ),
}
